name = "police-directory-cloud-api"
main = "cloudflare-worker/worker.js"
compatibility_date = "2024-04-01"

[[kv_namespaces]]
binding = "POLICE_KV"
id = "a0a531a02cc04d62a4f0bc375138a354"

[vars]
ADMIN_API_KEY = "police_admin_2026"
